### ISSUE TITLE
Can't expand/collapse any tree-view objects on the Source tab or debug popups

### ISSUE THREAD

**Issue by aovchinnikov** [node-inspector/node-inspector#584]
Env:

Windows 7
Chrome 41.0.2272.89 m
Node-inspector v0.9.2

Error:

Uncaught TypeError: undefined is not a function treeoutline.js:943 TreeElement.isEventWithinDisclosureTriangle treeoutline.js:643 TreeElement.treeElementToggled

**Comment by F4b1n0u** [comment]
same error on

MacOS 10.10.2
Chrome 41.0.2272.101 (64bits)
Node-inspectore v0.9.2

**Comment by fjurcovici** [comment]
Same on Chrome Version 41.0.2272.89 on Ubuntu 14.04.2 LTS 
uname --all says: 
Linux tim-lap-051 3.13.0-39-generic #66-Ubuntu SMP Tue Oct 28 13:31:23 UTC 2014 i686 i686 i686 GNU/Linux

**Comment by jmm** [comment]
Same here (Win 7 x64). It worked fine in my previous version of chrome (36 I think), but since updating to 41 it's pretty broken. Right now with repeated clicks I can sometimes get a tree to expand, but I can't get them to collapse.

**Comment by Chris911** [comment]
+1 on OS X and Chrome latest.

**Comment by 3y3** [comment]
Fixed in `0.10.0` release. Reopen this bug if the problem still persists for you.

**Comment by jmm** [comment]
Awesome, thanks @3y3! I just updated and tried it real quick (in Chrome 42 now) and so far so good. (To get the ball rolling I did have to pass a `--web-host` option when starting it that I didn't have to before.)

**Comment by F4b1n0u** [comment]
works great for me now, big thanks :)
