### ISSUE TITLE
Node 8.0

### ISSUE THREAD

**Issue by MatthD** [node-inspector/node-inspector#1010]
Hello it seems this package is not working with the new node 8.0 version ; 

Error at building 

'error: no member named 'GetMirror' in 'v8::Debug'
          v8::Debug::GetMirror(info.GetIsolate()->GetCurrentContext(), info[0]);'

**Comment by hustxiaoc** [comment]
Node8 brings a big break change in the debug api which is too difficult to implement in Node Inspector.  Besides it provides a built-in DevTools-based debugger which mostly deprecates Node Inspector. So basically you can just use the built-in debugger tools. https://nodejs.org/en/docs/inspector/

**Comment by mansona** [comment]
It's not true that we can just use the built-in debugger tools because of the unresolved issue of VM contexts https://github.com/nodejs/node/issues/7593 

There are some codebases that still require node-inspector like Ember-Fastboot

**Comment by snowinferno** [comment]
The built-in node 8 inspector fails to provide an interface for viewing the Network traffic originated by the application.
I have used that feature of `node-inspector` numerous times and am very sad to see that it is not available from the built-in inspector.

I would say it definitely does not deprecate Node inspector entirely, but I understand that it is a huge effort to update to the new APIs.

**Comment by michahell** [comment]
If I can offer a slight suggestion: maybe, just... maybe, it's good to include this info on the front page of the README.MD. So people can like, find that information and stuff. You know ehh, so they don't have to dig through issues to find out something trivial such as the most recent version of node-inspector not working with the most recent version of node. which is kind of neat, right ?

ffs
