### ISSUE TITLE
enter key in console and "add watch expression" performs line-break not execute

### ISSUE THREAD

**Issue by NilsFrkal** [node-inspector/node-inspector#903]
When entering commands/variables in the console (both break-point and non-break-point scenarios) or when specifying a variable under "add watch expression" the "enter" key does not execute the command/variable, but does a line-break instead. I could not find any other way to actually execute the command in the console. How can this behavior be changed or is this a bug? Thank you very much.

node-inspector version 0.12.8
nodejs 5.12.0
chrome Version 54.0.2824.0 dev-m (64-bit)

**Comment by corsen2000** [comment]
Having the same issue. Any advice?

**Comment by NilsFrkal** [comment]
I did not work out how to fix it. Interestingly however, I had this issue on both my desktop and my laptop. Because of an issue I had to revert back to an older backup for my desktop (this backup did not have node inspector and chrome installed). After re-installing above sws the issue did not occur anymore whilst on the laptop it still exists. If you have time try de-installing both chrome and node-inspector and re-install.

**Comment by ac9** [comment]
I ran into this same issue. I could not fix it by reinstalling chrome and node-inspector.
I could only fix it by rolling back to Version 51.0.2704.106 (64-bit). 

node-inspector version 0.12.8
nodejs v4.2.2
Chrome 54.0.2840.59
OS X El Capitan Version 10.11.6

**Comment by elliotatRetireup** [comment]
I'm not sure if its related, but I have the same issue as of yesterday. I didn't change anything I was doing with inspector. Can't fix by restarting anything. 

Since this issue showed up, I have noticed inconsistent behavior with the inspector. For instance, getting an 'is not a function' error for using .toLowerCase() on a string... only sometimes though.

Then I noticed the same thing happening with console.log(). I have no clue why this is happening but would love to be able to fix this

**Comment by newpost** [comment]
i have same issue

**Comment by pyalxx** [comment]
Same issue here

OS: macOS Sierra 10.12.1
Chrome: Version 54.0.2840.71 (64-bit)
node-inpector: 0.12.8

Note: same issue in watch - enter starts a new line

**Comment by ejhayes** [comment]
It looks like this issue might be related to a Chrome update in [54.0.2840.71](https://googlechromereleases.blogspot.com/2016/10/stable-channel-update-for-desktop.html).  I rolled back to `51.0.2704.106` (https://google-chrome.en.uptodown.com/mac/old, the link to `53.0.2785.101` was broken) which resolved the issue.

- Node: 4.2.6
- OS: El Cap 10.11.3
- Chrome: 54.0.2840.71 (previous version 51.0.2704.106 works)

**Comment by pyalxx** [comment]
Confirmed, working fine on 51.0.2704.84 (64-bit) Chrome

**Comment by Mido22** [comment]
people, I am kinda struck, no official option to downgrade chrome in windows, (and I don't trust 3rd party stuff), so would request a higher priority to solving this bug.

**Comment by emimull** [comment]
same here. on windows. stuck.

**Comment by Mido22** [comment]
good news, found a temporary work around, retrieved [chromium `53.0.2785.34`](https://commondatastorage.googleapis.com/chromium-browser-snapshots/index.html?prefix=Win_x64/389148/), so it is kinda official/ trust-able, you can find how to retrieve older chromium versions [here](https://www.chromium.org/getting-involved/download-chromium)

Bad news, tried chrome canary `v56`, the issue persists in that too.

**Comment by iamfrontender** [comment]
Look for workaround at:
https://github.com/node-inspector/node-inspector/pull/942

**Comment by sebastianconcept** [comment]
Having this issue on OS X
I'm using this one that seems to be okay 
https://commondatastorage.googleapis.com/chromium-browser-snapshots/index.html?prefix=Mac/389140/

**Comment by devmi** [comment]
If you would prefer to change node-inspector code _instead of downgrading Chrome_, here is a [nice fix](https://github.com/node-inspector/node-inspector/issues/951#issuecomment-262441472) (tested on Chrome 54.0.02840.98, Mac OS X, node-inspector v0.12.8)

**Comment by neutrino84** [comment]
the edit in #951 works perfectly for me, i'm pretty sure that pull request should be accepted, it's a simple change, how can it be failing a test???

**Comment by Lexicality** [comment]
Looks like the test just timed out. Anyone with write access should be able to re-run it.

**Comment by a7madgamal** [comment]
can someone please re-run the test?

**Comment by kubakoz** [comment]
If anyone is still having this problem, I just created a solution in the form of a chrome extension.

Thanks to some insights I've read online about the nature of this issue, I made a simple "hack" that will resolve the problem. 

https://chrome.google.com/webstore/detail/tizen-console-fix/hfpknnioheddhjmjhchindnmcoadmekl

Let me know if it works for you!

**Comment by hustxiaoc** [comment]
This issue had been solved in https://github.com/node-inspector/node-inspector/pull/1006

**Comment by szebenyib** [comment]
It still did not work for me, but @kubakoz 's plugin has helped! Many thanks 👍

**Comment by linegel** [comment]
At the end, is this issue solved or not?
